const USER_JOINED = 'USER_JOINED'
const GET_USERS_ONLINE = 'GET_USERS_ONLINE'
const USER_LEFT = 'USER_LEFT'
const NEW_MESSAGE = 'NEW_MESSAGE'
const JOIN_CHAT = 'JOIN_CHAT'
const VERIFY_CHAT = 'VERIFY_CHAT'
const WRONG_CHAT = 'WRONG_CHAT'
const CHAT_DOESNT_EXIST = 'CHAT_DOESNT_EXIST'
const RECONNECT_WITH_CHATID = 'RECONNECT_WITH_CHATID'
const NEW_CHAT = 'NEW_CHAT'
const FRIEND_IS_TYPING = 'FRIEND_IS_TYPING'
const GET_CHAT_PARAMS = 'GET_CHAT_PARAMS'

module.exports = {
  USER_JOINED,
  GET_USERS_ONLINE,
  USER_LEFT,
  NEW_MESSAGE,
  JOIN_CHAT,
  VERIFY_CHAT,
  CHAT_DOESNT_EXIST,
  WRONG_CHAT,
  RECONNECT_WITH_CHATID,
  NEW_CHAT,
  FRIEND_IS_TYPING,
  GET_CHAT_PARAMS,
}
